service: photo-viewer-api

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:GetItem
      Resource:
        - arn:aws:dynamodb:eu-west-1:${aws:accountId}:table/photoViewer
        - arn:aws:dynamodb:eu-west-1:${aws:accountId}:table/photoVectors
    - Effect: Allow
      Action:
        - dynamodb:Query # Specific permission for getFilters to query the new table
      Resource:
        - arn:aws:dynamodb:eu-west-1:${aws:accountId}:table/PhotoViewerFilters

  environment:
    TABLE_NAME: photoViewer
    VECTOR_TABLE_NAME: photoVectors
    FILTERS_TABLE_NAME: PhotoViewerFilters # Added for the new filters table
    QDRANT_HOST: '3.255.247.148'
    QDRANT_PORT: 6333
    COLLECTION_NAME: 'photo_embeddings'
    S3_BUCKET: 'trackphotos-eu-west-1'

functions:
  getFilters:
    handler: handlers/getFilters.handler
    events:
      - http:
          path: filters
          method: get
          cors: true

  getPhotos:
    handler: handlers/getPhotos.handler
    events:
      - http:
          path: photos
          method: get
          cors: true
          
  getSimilarPhotos:
    handler: handlers/getSimilarPhotos.handler
    timeout: 30
    memorySize: 1024
    events:
      - http:
          path: similar
          method: get
          cors: true

plugins:
  - serverless-offline
